driftwood:
  enable: true
  levels:
    '*': trace
poll:
  eagerInterval: 30
  defaultInterval: 60
slack:
  username: ghlack-dev
users:
  # oliverwoodings:
  #   githubToken: foo
  #   slack:
  #     hook: bar
  #     user: oli
